### ISSUE TITLE
libdevice not found error for a fresh Careless install

### ISSUE THREAD

**Issue by DHekstra** [rs-station/careless#101]
While setting up a dedicated conda environment at S3DF, a compute facility used by LCLS, Fred Poitevin and I encountered the following error when running Careless for the first time:

`Traceback (most recent call last):
  File "/sdf/group/lcls/ds/tools/conda_envs/careless/bin/careless", line 8, in <module>
    sys.exit(main())
  File "/sdf/group/lcls/ds/tools/conda_envs/careless/lib/python3.9/site-packages/careless/careless.py", line 9, in main
    run_careless(parser)
  File "/sdf/group/lcls/ds/tools/conda_envs/careless/lib/python3.9/site-packages/careless/careless.py", line 53, in run_careless
    history = model.train_model(
  File "/sdf/group/lcls/ds/tools/conda_envs/careless/lib/python3.9/site-packages/careless/models/merging/variational.py", line 173, in train_model
    _history = train_step((self, data))
  File "/sdf/group/lcls/ds/tools/conda_envs/careless/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/sdf/group/lcls/ds/tools/conda_envs/careless/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError: Graph execution error:

Detected at node 'StatefulPartitionedCall_24' defined at (most recent call last):
    File "/sdf/group/lcls/ds/tools/conda_envs/careless/bin/careless", line 8, in <module>
      sys.exit(main())
    File "/sdf/group/lcls/ds/tools/conda_envs/careless/lib/python3.9/site-packages/careless/careless.py", line 9, in main
      run_careless(parser)
    File "/sdf/group/lcls/ds/tools/conda_envs/careless/lib/python3.9/site-packages/careless/careless.py", line 53, in run_careless
      history = model.train_model(
    File "/sdf/group/lcls/ds/tools/conda_envs/careless/lib/python3.9/site-packages/careless/models/merging/variational.py", line 173, in train_model
      _history = train_step((self, data))
    File "/sdf/group/lcls/ds/tools/conda_envs/careless/lib/python3.9/site-packages/careless/models/merging/variational.py", line 159, in train_step
      history = model.train_step((data,))
    File "/sdf/group/lcls/ds/tools/conda_envs/careless/lib/python3.9/site-packages/keras/engine/training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/sdf/group/lcls/ds/tools/conda_envs/careless/lib/python3.9/site-packages/keras/optimizers/optimizer.py", line 543, in minimize
      self.apply_gradients(grads_and_vars)
    File "/sdf/group/lcls/ds/tools/conda_envs/careless/lib/python3.9/site-packages/keras/optimizers/optimizer.py", line 1174, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "/sdf/group/lcls/ds/tools/conda_envs/careless/lib/python3.9/site-packages/keras/optimizers/optimizer.py", line 650, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "/sdf/group/lcls/ds/tools/conda_envs/careless/lib/python3.9/site-packages/keras/optimizers/optimizer.py", line 1200, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "/sdf/group/lcls/ds/tools/conda_envs/careless/lib/python3.9/site-packages/keras/optimizers/optimizer.py", line 1250, in _distributed_apply_gradients
_fn
      distribution.extended.update(
    File "/sdf/group/lcls/ds/tools/conda_envs/careless/lib/python3.9/site-packages/keras/optimizers/optimizer.py", line 1245, in apply_grad_to_update_var
      return self._update_step_xla(grad, var, id(self._var_key(var)))
Node: 'StatefulPartitionedCall_24'
libdevice not found at ./libdevice.10.bc
         [[{{node StatefulPartitionedCall_24}}]] [Op:__inference_train_step_6403]
`

**Comment by DHekstra** [comment]
I suspect this is due to a missing package as specified at the end of the TensorFlow installation instructions at https://www.tensorflow.org/install/pip#step-by-step_instructions and will follow the recommendations at the end of section 6 thereof. We'll report back.
