### ISSUE TITLE
ValueError during Robust Merging for Sulfur SAD

### ISSUE THREAD

**Issue by gyuhyeokcho** [rs-station/careless#79]
I set up the careless to colab.

After successful installation of careless, when I run this,
!careless mono \
    --studentt-likelihood-dof=16 \
    --anomalous  \
    --disable-image-scales \
    --merge-half-datasets \
    --iterations=30_000 \
    "BATCH,dHKL,Hobs,Kobs,Lobs,XDET,YDET,BG,SIGBG,LP,QE,FRACTIONCALC" \
    unmerged.mtz \
    merge/studentt/hewl

I face this ValueError.
Traceback (most recent call last):
  File "/usr/local/bin/careless", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/careless/careless.py", line 9, in main
    run_careless(parser)
  File "/usr/local/lib/python3.8/dist-packages/careless/careless.py", line 88, in run_careless
    for file_id, ds_train in enumerate(dm.get_predictions(model, train)):
  File "/usr/local/lib/python3.8/dist-packages/careless/io/manager.py", line 101, in get_predictions
    ipred,sigipred = model.prediction_mean_stddev(inputs)
  File "/usr/local/lib/python3.8/dist-packages/careless/models/merging/variational.py", line 73, in prediction_mean_stddev
    f4 = q.moment_4(method='scipy')
  File "/usr/local/lib/python3.8/dist-packages/careless/models/merging/surrogate_posteriors.py", line 97, in moment_4
    return self._scipy_moment_4(high)
  File "/usr/local/lib/python3.8/dist-packages/careless/models/merging/surrogate_posteriors.py", line 81, in _scipy_moment_4
    mom4 = truncnorm.moment(4, a, b, loc, scale)
  File "/usr/local/lib/python3.8/dist-packages/scipy/stats/_distn_infrastructure.py", line 1274, in moment
    if not (self._argcheck(*args) and (scale > 0)):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 1070, in __bool__
    return bool(self._numpy())
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Generating these files for output.
checkpoint
hewl_0.mtz
hewl_data_manager.pickle
hewl_history.csv
hewl_scale.data-00000-of-00001
hewl_scale.index
hewl_structure_factor.data-00000-of-00001
hewl_structure_factor.index

Leaving these two files ungenerated
hewl_predictions_0.mtz
hewl_xval_0.mtz

How to solve this problem?

**Comment by kmdalton** [comment]
Hi @gyuhyeokcho,

Thanks for this issue! I have to confess that I had never tried to run careless on Colab before. So, this was a bit of a blind spot for me. However, I was eventually able to replicate your issue. 

I learned that careless tends to be tested against fairly current versions of `scipy` compared to what is provided by default on Google Colab. In order to run correctly, I found I had to upgrade scipy before calling careless. The following commands worked for me on Colab: 

```
!pip install --upgrade pip
!pip install --upgrade scipy
!pip install careless
!git clone https://github.com/rs-station/careless-examples
!mkdir -p merge/studentt
!careless mono \
--studentt-likelihood-dof=16 \
--anomalous \
--disable-image-scales \
--merge-half-datasets \
--iterations=30_000 \
"BATCH,dHKL,Hobs,Kobs,Lobs,XDET,YDET,BG,SIGBG,LP,QE,FRACTIONCALC" \
careless-examples/hewl_ssad/unmerged.mtz \
merge/studentt/hewl
```

Let me know if it works for you, and I will close this issue.

**Comment by gyuhyeokcho** [comment]
It worked for me as well!
